# Generated by Django 4.2.6 on 2023-11-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_store',
            name='record',
            field=models.FileField(unique=True, upload_to='media/'),
        ),
    ]
