# Generated by Django 4.2.6 on 2023-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arga', '0002_alter_audio_store_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_store',
            name='record',
            field=models.FileField(upload_to='media/'),
        ),
    ]
